# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
# - task: katalonTask@1
#   inputs:
#     version: '8.6.8'
#     executeArgs: '-retry=0 -testSuiteCollectionPath="Test Suites/Test Suite Collection_EndToEnd" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true -apiKey="8e69b787-3597-4859-be01-e5b8de2c5d56"'
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/APITestSuite" -browserType="Firefox" -executionProfile="default" -apiKey="8e69b787-3597-4859-be01-e5b8de2c5d56" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Junit'
    testRunTitle: 'Smoke_EndToEnd Test Log'
    testResultsFiles: '**/Test Suite Collection_EndToEnd/**/JUnit_Report.xml'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/Reports'
    artifact: 'Test Reports'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
