# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-retry=0 -testSuiteCollectionPath="Test Suites/Test Suite Collection_EndToEnd" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true -apiKey="873bd645-8caf-4061-9591-b3fa6c2abe46"'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Junit'
    testRunTitle: 'Smoke_EndToEnd Test Log'
    testResultsFiles: '**/JUnit_Report.xml'
  condition: succeededOrFailed()
- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(Build.SourcesDirectory)/HTML_Report.html'
  condition: succeededOrFailed()