
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: ' -retry=0 -testSuitePath="Test Suites/Smoke_EndToEnd" -browserType="Remote" -executionProfile="default" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
