
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: ' -retry=0 -testSuitePath="Test Suites/Smoke_EndToEnd" -browserType="Remote" -executionProfile="default"-apiKey="873bd645-8caf-4061-9591-b3fa6c2abe46" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
