# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/Smoke_EndToEnd" -browserType="Chrome" -executionProfile="default" -apiKey="8fdc1673-2d9d-46ac-a1ba-f74b2013368f" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
