<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart</name>
   <tag></tag>
   <elementGuidId>58321366-deb0-4459-9bed-982a617a60eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-add-to-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-add-to-cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>832899c8-7427-4d20-84ac-3947f2458338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>add-to-cart</value>
      <webElementGuid>02b78bcc-2597-4d23-8e15-3bcddc6bded6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-add-to-cart</value>
      <webElementGuid>5e37d1d9-ef62-40f6-a1a6-3fdfe8392c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-success btn</value>
      <webElementGuid>9cc7e2c5-25d8-4d91-bff4-b44479940ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart </value>
      <webElementGuid>00687a3d-fbe5-47a1-86bd-db845e9b4160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-add-to-cart&quot;)</value>
      <webElementGuid>2fb07380-8d87-492f-afb8-1ac256bc2d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-add-to-cart']</value>
      <webElementGuid>c15c603b-6778-4d8d-8250-9bb6eb1f617d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand name 1'])[1]/following::button[3]</value>
      <webElementGuid>3ebd2d21-d4e8-46e9-b9a1-4b7c071e04fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to favourites'])[1]/preceding::button[1]</value>
      <webElementGuid>4a9d998c-b2eb-4433-abc5-f350233a5062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Related products'])[1]/preceding::button[2]</value>
      <webElementGuid>2b7e2dfd-5c42-4329-a08c-93f6c673e66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to cart']/parent::*</value>
      <webElementGuid>2874c919-55cb-4bd2-a20a-9cac4625c12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>51c49570-a331-4d00-a664-581a2d62e471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-add-to-cart' and (text() = 'Add to cart ' or . = 'Add to cart ')]</value>
      <webElementGuid>5ea88692-ab6e-4666-9a6d-d802e22632a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
