<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_paymentMethod</name>
   <tag></tag>
   <elementGuidId>5ce9166a-968d-491d-9f71-b9a48efff139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='payment-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0d9ceebb-ca54-4fe7-b0ff-37e84805af8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>ecfb2e14-0c88-4904-bf64-3d3b7086ed36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>4542e088-5f7d-4502-a55f-4c04a491e658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>dade4c5c-77d8-4696-9d3a-01ec448155a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5c11e0e1-179a-4d4e-9ba3-0fba9a39a2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card</value>
      <webElementGuid>ebec82a8-8ee2-4b30-ae4c-9274503b1706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method&quot;)</value>
      <webElementGuid>b49679e2-b537-4c2f-9491-975efa8f4c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='payment-method']</value>
      <webElementGuid>92afed7c-3837-46e0-a946-013fe8d220dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[2]/following::select[1]</value>
      <webElementGuid>773fd365-c3ba-4509-b8b1-5d95abacd8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to checkout'])[3]/following::select[1]</value>
      <webElementGuid>873e7c8e-7466-4825-9cde-8a5e534e1d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::select[1]</value>
      <webElementGuid>23e461ea-f6e7-4bcb-8167-d428a0985d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub repo'])[1]/preceding::select[1]</value>
      <webElementGuid>9e8ad340-4a07-45e0-868f-26bf7883cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c8ee38e4-0810-49d8-a1bf-849bbb89e6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'payment-method' and (text() = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card' or . = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card')]</value>
      <webElementGuid>37268f85-60a9-42e0-8051-b74177b99098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
