<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose your monthly installments</name>
   <tag></tag>
   <elementGuidId>b6e7315f-3830-48ff-8f24-ef69dda3b45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='monthly_installments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthly_installments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cdf98ff6-5bce-46be-8af7-03f7016f2d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>monthly_installments</value>
      <webElementGuid>9e8765b2-2e1c-4e0b-8a68-5f06515b1581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthly_installments</value>
      <webElementGuid>d3cd5b23-5df2-4a16-b3d4-648e3425bad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>monthly_installments_help</value>
      <webElementGuid>308cd28b-6519-4616-9c7b-91433ef6b19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>monthly_installments</value>
      <webElementGuid>d696ddcf-527c-47d5-8dab-0f78003cf9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>13a75cf7-d261-446d-9ada-f62e6f7db32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your monthly installments3 monthly installments6 monthly installments9 monthly installments12 monthly installments</value>
      <webElementGuid>7065a376-7f69-4558-b3c3-f413fa4088ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthly_installments&quot;)</value>
      <webElementGuid>5fb7d4db-cd31-4853-acc6-9ccb08f98ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='monthly_installments']</value>
      <webElementGuid>0f7a7504-3460-4d46-b38f-bbd60912cf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[2]/following::select[2]</value>
      <webElementGuid>d261220b-f2c7-4b02-b029-2112b69f5ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to checkout'])[3]/following::select[2]</value>
      <webElementGuid>0391c3bd-0ff1-4cb9-a311-059d83ec39ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This option allows you to spread the cost of your purchase over several months.'])[1]/preceding::select[1]</value>
      <webElementGuid>b6f6347e-b542-4e1a-99af-7aedd421c8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::select[1]</value>
      <webElementGuid>0af7183d-8d4f-4789-9d56-bd8f26d1f8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>46fb2541-4617-41d0-9425-fc8455bc7607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'monthly_installments' and (text() = 'Choose your monthly installments3 monthly installments6 monthly installments9 monthly installments12 monthly installments' or . = 'Choose your monthly installments3 monthly installments6 monthly installments9 monthly installments12 monthly installments')]</value>
      <webElementGuid>5626ab97-8bcb-4e28-9f48-c23f277d279a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
