<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_creditCardNumber</name>
   <tag></tag>
   <elementGuidId>a8513858-9a78-4d45-8739-5416a777a8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-payment/div/div/div/form/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.ng-dirty.ng-valid.ng-touched > div:nth-of-type(2) > input.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b49497d-90f5-42c6-b4b3-b61ccbf5ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>credit_card_number</value>
      <webElementGuid>e3eea76a-4d27-4a28-aa96-6797b37b122e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>credit_card_number_help</value>
      <webElementGuid>3e8beb61-d249-4ff4-a003-7e6fbedac7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Credit Card Number</value>
      <webElementGuid>ccdb0568-e44a-490e-ba4c-3f29f6527ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>415bce11-a5b7-4ed2-bca1-19dcf8283390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;container&quot;]/app-checkout[1]/aw-wizard[@class=&quot;horizontal&quot;]/div[@class=&quot;wizard-steps horizontal&quot;]/aw-wizard-completion-step[1]/app-payment[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 offset-md-3 login-form-1&quot;]/form[@class=&quot;ng-dirty ng-valid ng-touched&quot;]/div[2]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d9c84608-3c05-48dd-a40c-b3914d73c858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-payment/div/div/div/form/div[2]/input</value>
      <webElementGuid>c1983dd2-f504-4117-a812-7144c4154c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Credit Card Number']</value>
      <webElementGuid>7f4a9342-e9c3-4036-8312-18d3b40062c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
