<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_cardHolderName</name>
   <tag></tag>
   <elementGuidId>6d6ccb39-1b7d-4553-bd40-c96ceecc7995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.mb-3.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>031a27fb-371b-4606-937c-d7fc515d14ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>card_holder_name</value>
      <webElementGuid>6d289c20-d4bc-4565-8198-0dcba98696bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card Holder Name</value>
      <webElementGuid>c8b2ccd6-a2fc-48cf-8f05-b3beb251dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9dca1cb3-95e8-4347-88ac-d2f7f389d6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;container&quot;]/app-checkout[1]/aw-wizard[@class=&quot;horizontal&quot;]/div[@class=&quot;wizard-steps horizontal&quot;]/aw-wizard-completion-step[1]/app-payment[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 offset-md-3 login-form-1&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[2]/input[@class=&quot;form-control mb-3 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>8a543253-ae96-4235-8308-7b389e1c1bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>cee2e9c7-b297-46c1-9541-fdde4fb0acb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Card Holder Name']</value>
      <webElementGuid>ffbf7890-fe13-4d3a-a11f-27a18e88535d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
