<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBox_Postcode</name>
   <tag></tag>
   <elementGuidId>d5885cdb-1839-4c63-a6db-b09ff8c3b25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b39ba13-8221-4d5d-8ba0-b9524d535213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>19b1bfa0-fb7c-402f-b36a-bc074c223dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>54cee10c-7ee3-4541-a811-40e49b9a4ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>372f7deb-f8a4-4119-9c88-e6eff006b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ca56e58-a9f8-49aa-b4e8-8c818e636638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your postcode *</value>
      <webElementGuid>717885c7-58ab-44b6-b7f7-ca5c01d319ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b05daa6b-345c-4a89-9c8d-10db40e68c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postcode&quot;)</value>
      <webElementGuid>9f316cf6-aa8a-4340-900b-0a762693c84a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postcode']</value>
      <webElementGuid>12220622-5883-4b3b-aafb-0417b50dcb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>e793f37d-f667-4c07-b4dd-06c30a272bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postcode' and @type = 'text' and @placeholder = 'Your postcode *']</value>
      <webElementGuid>9e5e8def-5178-450c-bc64-e64459b3d43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
