<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose your payment methodBank Trans_920188</name>
   <tag></tag>
   <elementGuidId>94d520f2-c649-4524-a7f6-2b4a06113b49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='payment-method']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-method</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c40d43c8-4f2e-4298-9302-a490e523a742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>c627ecfd-622e-4ea4-a750-ec8c1e94aefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>20da8f2d-2637-4a86-9a7e-adde723d90bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>4d8164a4-1462-41d4-bbce-0e56eed3e12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cc065fd1-6738-4b67-a777-3645127bf168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card</value>
      <webElementGuid>31e93886-ea06-4bb0-8969-60e688c86402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method&quot;)</value>
      <webElementGuid>c0551ff5-f5a2-456a-8da0-bc7868342e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='payment-method']</value>
      <webElementGuid>0cf2a08c-960f-4dbb-9c36-8764652c8f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[2]/following::select[1]</value>
      <webElementGuid>3b2b498a-da96-4011-b6d9-1fff5eb2c2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to checkout'])[3]/following::select[1]</value>
      <webElementGuid>3ee92907-f4d2-4325-8379-b94391e12a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::select[1]</value>
      <webElementGuid>18a31d4b-d053-4a75-8456-99b657aa836d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub repo'])[1]/preceding::select[1]</value>
      <webElementGuid>32441123-e9bd-4369-a4cf-125f131cad6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>63ffc3a3-3f92-4ae6-9ca2-6135e7171c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'payment-method' and (text() = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card' or . = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card')]</value>
      <webElementGuid>dce1f353-a7ab-4c3d-9dfd-d7569689402c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
